app/cart/urls.py
from django.urls import path

from .views import cart_detail, cart_add, cart_remove

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('sign/', include('sign.urls')),
    path('staff/', include('staff.urls')),
    path('coupon/', include('coupons.urls')),
    path('product/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/staff/urls.py
from django.urls import path

from .views import (
    ManagementView,
    StaffListView,
    StaffRegisterView,
    StaffUpdateView,
    StaffAccountView,
    FiredListView,
    staff_remove_view,
    staff_restore_view,
)

urlpatterns = [
    path('', StaffListView.as_view(), name='staff_list'),
    path('signup/', StaffRegisterView.as_view(), name='staff_signup'),
    path('profile/<int:pk>/', StaffUpdateView.as_view(), name='staff_profile'),
    path('account/', StaffAccountView.as_view(), name='staff_account'),
    path('management/', ManagementView.as_view(), name='management'),
    path('remove/<int:pk>/', staff_remove_view, name='staff_remove'),
    path('restore/<int:pk>/', staff_restore_view, name='staff_restore'),
    path('fired/', FiredListView.as_view(), name='fired_list'),
]

app/staff/models.py
from django.db import models

from .constants import STAFF
from sign.models import CustomUser


# Модель для Персонала
class Staff(CustomUser):
    position = models.CharField(
        verbose_name='Должность',
        max_length=3,
        choices=STAFF,
        default='MNR'
    )
    contract = models.CharField(
        verbose_name='Номер трудового договора',
        max_length=32,
        unique=True
    )

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.middle_name}"

    def make_active(self):
        self.is_active = True
        self.save()

    def make_inactive(self):
        self.is_active = False
        self.save()

app/staff/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import Staff


class StaffRegisterForm(UserCreationForm):
    phone = forms.CharField(
        widget=forms.TextInput(attrs={
            'type': 'text',
            'onkeypress': 'return event.charCode === 0 || /\d/.test(String.fromCharCode(event.charCode))',
        }),
        label="Номер телефона: +7",
        label_suffix="",
        min_length=11,
        max_length=12,
        required=False,
    )
    birthdate = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date',
        }, format='%Y-%m-%d'),
        label="Дата рождения",
        required=False
    )

    class Meta:
        model = Staff
        fields = (
            "email",
            "username",
            "last_name",
            "first_name",
            "middle_name",
            "individual_taxpayer_number",
            "position",
            "contract",
            "birthdate",
            "city",
            "phone",
            "password1",
            "password2",
        )


class StaffUpdateForm(UserChangeForm):
    email = forms.EmailField(
        disabled=True
    )
    username = forms.CharField(
        label="Имя пользователя",
        disabled=True
    )
    phone = forms.CharField(
        widget=forms.TextInput(attrs={
            'type': 'text',
            'onkeypress': 'return event.charCode === 0 || /\d/.test(String.fromCharCode(event.charCode))',
        }),
        label="Номер телефона: +7",
        label_suffix="",
        min_length=11,
        max_length=12,
        required=False,
    )
    birthdate = forms.DateField(
        widget=forms.DateInput(attrs={
            'type': 'date',
        }, format='%Y-%m-%d'),
        label="Дата рождения",
        required=False
    )

    class Meta:
        model = Staff
        fields = (
            "email",
            "username",
            "last_name",
            "first_name",
            "middle_name",
            "individual_taxpayer_number",
            "position",
            "contract",
            "groups",
            "birthdate",
            "city",
            "phone",
            "telegram",
            "whatsapp",
            "viber",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        del self.fields["password"]

app/staff/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import ImproperlyConfigured
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView, ListView

from .forms import StaffRegisterForm, StaffUpdateForm
from .models import Staff


# Представление для просмотра всех сотрудников
class StaffListView(PermissionRequiredMixin, ListView):
    model = Staff
    ordering = '-last_name'
    template_name = 'staff/staff_list.html'
    context_object_name = 'staff'
    permission_required = ('staff.view_staff',)
    raise_exception = True
    paginate_by = 10

    def get_queryset(self):
        return Staff.objects.filter(is_active=True).order_by(self.ordering)


# Представление для просмотра всех уволенных сотрудников
class FiredListView(PermissionRequiredMixin, ListView):
    model = Staff
    ordering = '-last_name'
    template_name = 'staff/fired_list.html'
    context_object_name = 'fired'
    permission_required = ('staff.view_staff',)
    raise_exception = True
    paginate_by = 10

    def get_queryset(self):
        return Staff.objects.filter(is_active=False).order_by(self.ordering)


# Представление для регистрации работника
class StaffRegisterView(PermissionRequiredMixin, CreateView):
    model = Staff
    form_class = StaffRegisterForm
    template_name = 'staff/signup.html'
    permission_required = ('staff.add_staff',)
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = StaffRegisterForm()
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = True
            user.is_staff = True
            user.save()
            staff_group = Group.objects.get(name='staff')
            staff_group.user_set.add(user)
            return redirect('staff_list')
        else:
            return render(request, self.template_name, {'form': form})


class StaffUpdateView(PermissionRequiredMixin, UpdateView):
    model = Staff
    form_class = StaffUpdateForm
    template_name = 'staff/update.html'
    success_url = reverse_lazy('staff_list')
    permission_required = ('staff.change_staff',)
    raise_exception = True

    def get_permission_required(self):
        self.object = self.get_object()
        if not (
                self.request.user.email == self.object.email or
                self.request.user.is_superuser
        ):
            content = f'''
                <p style="font-size: 2em; font-weight: bold; font-family: Times New Roman;">403 Forbidden</p>
            '''
            return HttpResponse(content=content)
        if self.permission_required is None:
            raise ImproperlyConfigured(
                f"{self.__class__.__name__} is missing the "
                f"permission_required attribute. Define "
                f"{self.__class__.__name__}.permission_required, or override "
                f"{self.__class__.__name__}.get_permission_required()."
            )
        if isinstance(self.permission_required, str):
            perms = (self.permission_required,)
        else:
            perms = self.permission_required
        return perms


class StaffAccountView(PermissionRequiredMixin, TemplateView):
    template_name = 'staff/account.html'
    permission_required = ('staff.change_staff',)
    raise_exception = True

    def get_permission_required(self):
        if not (self.request.user.is_staff or self.request.user.is_superuser):
            content = f'''
                <p style="font-size: 2em; font-weight: bold; font-family: Times New Roman;">403 Forbidden</p>
            '''
            return HttpResponse(content=content)
        if self.permission_required is None:
            raise ImproperlyConfigured(
                f"{self.__class__.__name__} is missing the "
                f"permission_required attribute. Define "
                f"{self.__class__.__name__}.permission_required, or override "
                f"{self.__class__.__name__}.get_permission_required()."
            )
        if isinstance(self.permission_required, str):
            perms = (self.permission_required,)
        else:
            perms = self.permission_required
        return perms


class ManagementView(PermissionRequiredMixin, TemplateView):
    template_name = 'staff/management.html'
    permission_required = ('staff.change_staff', 'orders.view_order',)
    raise_exception = True

    def get_permission_required(self):
        if not (
                'management' in self.request.user.groups.all().values_list('name', flat=True) or
                self.request.user.is_superuser
        ):
            content = f'''
                <p style="font-size: 2em; font-weight: bold; font-family: Times New Roman;">403 Forbidden</p>
            '''
            return HttpResponse(content=content)
        if self.permission_required is None:
            raise ImproperlyConfigured(
                f"{self.__class__.__name__} is missing the "
                f"permission_required attribute. Define "
                f"{self.__class__.__name__}.permission_required, or override "
                f"{self.__class__.__name__}.get_permission_required()."
            )
        if isinstance(self.permission_required, str):
            perms = (self.permission_required,)
        else:
            perms = self.permission_required
        return perms


# Представление, делающее сотрудника активным
@permission_required('staff.change_staff', raise_exception=True)
def staff_restore_view(request, pk):
    # получаем сотрудника
    person = Staff.objects.get(id=pk)
    if not (
            'management' in request.user.groups.all().values_list('name', flat=True) or
            request.user.is_superuser
    ):
        content = f'''
            <p style="font-size: 2em; font-weight: bold; font-family: Times New Roman;">403 Forbidden</p>
        '''
        return HttpResponse(content=content)
    # меняем активность
    person.make_active()

    return redirect('fired_list')


# Представление, делающее сотрудника неактивным
@permission_required('staff.change_staff', raise_exception=True)
def staff_remove_view(request, pk):
    # получаем сотрудника
    person = Staff.objects.get(id=pk)
    if not (
            'management' in request.user.groups.all().values_list('name', flat=True) or
            request.user.is_superuser
    ):
        content = f'''
            <p style="font-size: 2em; font-weight: bold; font-family: Times New Roman;">403 Forbidden</p>
        '''
        return HttpResponse(content=content)
    # меняем активность
    person.make_inactive()

    return redirect('staff_list')

app/templates/staff/account.html
{% extends 'default.html' %}

{% block title %}
	Account
{% endblock title %}

{% block content %}
    <h2>Личный кабинет</h2>
	<hr>
	<button>
		<a href="{% url 'staff_profile' pk=request.user.pk %}">Настройка профиля</a>
	</button>
	{% for group in request.user.groups.all %}
		{% if group.name == 'management'  %}
			<button>
				<a href="{% url 'management' %}">Управление</a>
			</button>
		{% endif %}
	{% endfor %}
	<button>
		<a href="{% url 'order_list' %}">Заказы</a>
	</button>
{% endblock content %}

app/templates/staff/delete.html
{% extends 'default.html' %}

{% block content %}
    <h2>Удаление сотрудника</h2>
    <hr>
	{% for group in request.user.groups.all %}
		{% if group.name == 'management'  %}
            <form action="" method="post">
                {% csrf_token %}
                <p>Вы точно хотите удалить "
                    {{ object.last_name }}
                    {{ object.first_name }}
                    {% if object.middle_name is None %}

                    {% else %}
                        {{ object.middle_name }}
                    {% endif %}
                    "?
                </p>
                <hr>
                <input type="button" onclick="history.back();" value="Назад"/>
                <input type="submit" value="Удалить" />
            </form>
        {% endif %}
    {% endfor %}
{% endblock content %}

app/templates/staff/fired_list.html
{% extends 'default.html' %}

{% load custom_tags %}

{% block title %}
	Products
{% endblock title %}

{% block content %}
    <h2>Сотрудники</h2>
    <hr>
	{% for group in request.user.groups.all %}
		{% if group.name == 'management'  %}
            {% if fired %}
                <table cellpadding="10">
                    <tr>
                        <th>Фамилия</th>
                        <th>Имя</th>
                        <th>Отчество</th>
                        <th>ИНН</th>
                        <th>Должность</th>
                        <th>Номер трудового договора</th>
                    </tr>
                    {% for person in fired %}
                        <tr>
                            <td>{{ person.last_name }}</td>
                            <td>{{ person.first_name }}</td>
                            {% if person.middle_name is None %}
                                <td>-</td>
                            {% else %}
                                <td>{{ person.middle_name }}</td>
                            {% endif %}
                            <td>{{ person.individual_taxpayer_number }}</td>
                            <td>{{ person.get_position_display }}&nbsp;</td>
                            <td>{{ person.contract }}&nbsp;</td>
                            <td><button><a href="{% url 'staff_restore' pk=person.pk %}">Вернуть в штат</a></button></td>
                            <td><button><a href="{% url 'staff_profile' pk=person.pk %}">Изменить</a></button></td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>Уволенных сотрудников нет!</p>
            {% endif %}
	    {% endif %}
	{% endfor %}
	<!-- Добавляем пагинацию на страницу -->
	<!-- Информация о предыдущих страницах -->
	{% if paginator.num_pages != 1 %}
		{% if page_obj.has_previous %}
			<a href="?{% url_replace page=1 %}">&laquo;Первая</a>
			...
			<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
		{% endif %}
		<!-- Информация о текущей странице -->
		|{{ page_obj.number }}|
		<!-- Информация о следующих страницах -->
		{% if page_obj.has_next %}
			<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
			...
			<a href="?{% url_replace page=page_obj.paginator.num_pages %}">Последняя&raquo;</a>
		{% endif %}
	{% endif %}

{% endblock content %}

app/templates/staff/management.html
{% extends 'default.html' %}

{% block title %}
	Management
{% endblock title %}

{% block content %}
    <h2>Панель управления</h2>
	<hr>
	<button>
		<a href="{% url 'staff_list' %}">Сотрудники</a>
	</button>
	<button>
		<a href="{% url 'report' %}">Отчеты</a>
	</button>
{% endblock content %}

app/templates/staff/signup.html
{% extends "default.html" %}

{% block title %}
	Staff Sign Up
{% endblock title %}

{% block content %}
	<h2> Регистрация сотрудника</h2>
	<hr>
	{% for group in request.user.groups.all %}
		{% if group.name == 'management'  %}
			<form method="post" action="">
				{% csrf_token %}
				{{ form.as_p }}
				<hr>
				<input type="button" onclick="history.back();" value="Назад"/>
				<input type="submit" value="Продолжить">
			</form>
		{% endif %}
	{% endfor %}
{% endblock content %}

app/templates/staff/staff_list.html
{% extends 'default.html' %}

{% load custom_tags %}

{% block title %}
	Staff
{% endblock title %}

{% block content %}
    <h2>Сотрудники</h2>
    <hr>
	{% for group in request.user.groups.all %}
		{% if group.name == 'management'  %}
			<button>
				<a href="{% url 'staff_signup' %}">Добавить нового сотрудника</a>
			</button>
			<button>
				<a href="{% url 'fired_list' %}">Уволенные сотрудники</a>
			</button>
			{% if staff %}
				<table cellpadding="10" align="center">
					<tr>
						<th>Фамилия</th>
						<th>Имя</th>
						<th>Отчество</th>
						<th>ИНН</th>
						<th>Должность</th>
						<th>Номер трудового договора</th>
					</tr>
					{% for person in staff %}
						<tr>
							<td>{{ person.last_name }}</td>
							<td>{{ person.first_name }}</td>
							{% if person.middle_name is None %}
								<td>-</td>
							{% else %}
								<td>{{ person.middle_name }}</td>
							{% endif %}
							<td>{{ person.individual_taxpayer_number }}</td>
							<td>{{ person.get_position_display }}&nbsp;</td>
							<td>{{ person.contract }}&nbsp;</td>
							<td><button><a href="{% url 'staff_profile' pk=person.pk %}">Изменить</a></button></td>
							<td><button><a href="{% url 'staff_remove' pk=person.pk %}">Удалить</a></button></td>
						</tr>
					{% endfor %}
				</table>
			{% else %}
				<p>Сотрудников нет!</p>
			{% endif %}
		{% endif %}
	{% endfor %}
	<!-- Добавляем пагинацию на страницу -->
	<!-- Информация о предыдущих страницах -->
	{% if paginator.num_pages != 1 %}
		{% if page_obj.has_previous %}
			<a href="?{% url_replace page=1 %}">&laquo;Первая</a>
			...
			<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
		{% endif %}
		<!-- Информация о текущей странице -->
		|{{ page_obj.number }}|
		<!-- Информация о следующих страницах -->
		{% if page_obj.has_next %}
			<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
			...
			<a href="?{% url_replace page=page_obj.paginator.num_pages %}">Последняя&raquo;</a>
		{% endif %}
	{% endif %}

{% endblock content %}

app/templates/staff/update.html
{% extends 'default.html' %}

{% block title %}
	Profile
{% endblock title %}

{% block content %}
    <h2>Профиль</h2>
	<hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>
            <a href="{% url 'password_change' %}">Изменить пароль</a>
        </button>
        <hr>
        <input type="button" onclick="history.back();" value="Назад"/>
        <input type="submit" value="Сохранить"/>
    </form>

{% endblock content %}